-- G_WIPINV_DEFECT的DEFECT_CODE和SYS_DEFECT具相依性
-- UPDATE_TIME是看G表
SELECT
    TO_CHAR(g.UPDATE_TIME, 'YYYY-MM-DD') AS 日期,
    g.PROCESS_ID,
    g.DEFECT_CODE,
    s.DEFECT_NAME,
    SUM(g.DEFECT_QTY) AS DEFECT_QTY
FROM G_WIPINV_DEFECT g
LEFT JOIN SYS_DEFECT s
    ON g.DEFECT_CODE = s.DEFECT_CODE
WHERE g.DEFECT_CODE IN ('M015', 'M017', 'M018', 'M019', 'M020', 'M021')
  AND g.UPDATE_TIME <= TO_DATE('2026-07-08', 'YYYY-MM-DD')
GROUP BY
    TO_CHAR(g.UPDATE_TIME, 'YYYY-MM-DD'),
    g.PROCESS_ID,
    g.DEFECT_CODE,
    s.DEFECT_NAME
ORDER BY
    日期,
    g.PROCESS_ID,
    g.DEFECT_CODE;
   
